export const KAFKA_GROUP_ID = "KAFKA_GROUP_ID";
export const KAFKA_BROKERS = "KAFKA_BROKERS";
export const KAFKA_CLIENT_ID = "KAFKA_CLIENT_ID";
export const KAFKA_CLIENT_CONFIG_SSL = "KAFKA_CLIENT_CONFIG_SSL";
<<<<<<< HEAD
=======
export const KAFKA_CLIENT_CONSUMER_SESSION_TIMEOUT =
  "KAFKA_CLIENT_CONSUMER_SESSION_TIMEOUT";
export const KAFKA_CLIENT_CONSUMER_HEARTHBEAT =
  "KAFKA_CLIENT_CONSUMER_HEARTHBEAT";
>>>>>>> 46ef1fee2562a397e75dc75d8aa1b3e2356c30e9
