name: Release

on:
  workflow_call:
    inputs:
      branch:
        type: string
        description: Name of the git branch
        required: true
      affected-apps:
        type: string
        description: Nx applications affected by the changes
        required: true
      affected-lib:
        type: string
        description: Nx libraries affected by the changes
        required: true
<<<<<<< HEAD
      affected-dockerable:
        type: string
        description: Nx projects configured with docker:build affected by the changes
        required: true
      affected-deployable:
=======
      affected-package-container:
        type: string
        description: Nx projects configured with package:container affected by the changes
        required: true
      affected-deploy-static:
        type: string
        description: Nx projects configured with deploy:static affected by the changes
        required: true
      affected-deploy-container:
>>>>>>> 46ef1fee2562a397e75dc75d8aa1b3e2356c30e9
        type: string
        description: Nx projects configured with deploy affected by the changes
        required: true
    secrets:
<<<<<<< HEAD
      nx-cloud-access-token:
=======
      NX_CLOUD_ACCESS_TOKEN:
>>>>>>> 46ef1fee2562a397e75dc75d8aa1b3e2356c30e9
        required: true
      ECR_AWS_ACCESS_KEY_ID:
        required: true
      ECR_AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
env:
<<<<<<< HEAD
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.nx-cloud-access-token }}
=======
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
>>>>>>> 46ef1fee2562a397e75dc75d8aa1b3e2356c30e9
  BRANCH: ${{ inputs.branch }}
  CYPRESS_CACHE_FOLDER: node_modules/.cache/Cypress

jobs:
  package:
<<<<<<< HEAD
    if: ${{ inputs.affected-dockerable != '[]' && inputs.affected-dockerable != ''}}
=======
    if: ${{ inputs.affected-package-container != '[]' && inputs.affected-package-container != ''}}
>>>>>>> 46ef1fee2562a397e75dc75d8aa1b3e2356c30e9
    name: Package
    runs-on: ubuntu-20.04
    strategy:
      matrix:
<<<<<<< HEAD
        project: ${{ fromJson(inputs.affected-dockerable) }}
=======
        project: ${{ fromJson(inputs.affected-package-container) }}
>>>>>>> 46ef1fee2562a397e75dc75d8aa1b3e2356c30e9
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version-file: "package.json"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Cache global node modules
        id: cache-node-modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}

<<<<<<< HEAD
      - name: Cache other node modules
        id: cache-other-node-modules
        uses: actions/cache@v3
        env:
          cache-name: cache-other-node-modules
        with:
          path: |
            libs/data-service-generator/node_modules
            libs/util/code-gen-utils/node_modules
            packages/amplication-cli/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./**/package-lock.json') }}

=======
>>>>>>> 46ef1fee2562a397e75dc75d8aa1b3e2356c30e9
      - name: Install Dependencies
        if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' || steps.cache-other-node-modules.outputs.cache-hit != 'true' }}
        run: npm ci

      - name: Configure AWS Credentials (operations account)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR (operations account)
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: "439403303254"

      # https://github.com/docker/metadata-action
      - name: Docker Metadata
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: "439403303254.dkr.ecr.us-east-1.amazonaws.com/${{ matrix.project }}"
          tags: |
            type=sha,prefix=sha-
            type=ref,event=pr,prefix=pr-
            type=ref,event=tag,prefix=tag-
            type=raw,value=${{ github.run_id }},prefix=gh-
            type=raw,value=${{ env.BRANCH }}
            type=raw,value=latest,enable=${{ env.BRANCH == 'master' }}

      # https://www.npmjs.com/package/@nx-tools/nx-docker
      - name: Dockerize
<<<<<<< HEAD
        run: npx nx docker:build ${{ matrix.project }} --prod
=======
        run: npx nx package:container ${{ matrix.project }} --prod
>>>>>>> 46ef1fee2562a397e75dc75d8aa1b3e2356c30e9
        env:
          INPUT_TAGS: ${{ steps.meta.outputs.tags }}
          INPUT_PUSH: true
          # env variables substituted in the project.json docker target build-args
          GIT_REF_NAME: ${{ github.ref_name }}
          GIT_SHA: ${{ github.sha }}

  configure:
    name: Configure deployment target environment
    runs-on: ubuntu-20.04
    outputs:
      environment: ${{ steps.environment-identifier.outputs.environment }}
    steps:
      - id: environment-identifier
        run: |
          if [[ "${{ env.BRANCH }}" == "next" ]];
          then
            echo environment="sandbox" >> $GITHUB_OUTPUT
          elif [[ "${{ env.BRANCH }}" == "master" ]];
          then
            echo environment="staging" >> $GITHUB_OUTPUT
          fi;

<<<<<<< HEAD
  deploy:
    name: Deployment
    needs: [package, configure]
    if: ${{ inputs.affected-deployable != '[]' && inputs.affected-deployable != ''}}
    strategy:
      matrix:
        project: ${{ fromJson(inputs.affected-deployable) }}
    uses: ./.github/workflows/deployment.template.yml
    with:
      environment-name: ${{ needs.configure.outputs.environment }}
      project-name: ${{ matrix.project }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
=======
  deploy-container:
    name: Deployment container
    needs: [package, configure]
    if: ${{ inputs.affected-deploy-container != '[]' && inputs.affected-deploy-container != ''}}
    strategy:
      matrix:
        project: ${{ fromJson(inputs.affected-deploy-container) }}
    uses: ./.github/workflows/deployment.container.template.yml
    with:
      environment-name: ${{ needs.configure.outputs.environment }}
      project-name: ${{ matrix.project }}
      deploy-type: "container"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-static:
    name: Deployment static
    needs: [package, configure]
    if: ${{ inputs.affected-deploy-static != '[]' && inputs.affected-deploy-static != ''}}
    strategy:
      matrix:
        project: ${{ fromJson(inputs.affected-deploy-static) }}
    uses: ./.github/workflows/deployment.static.template.yml
    with:
      environment-name: ${{ needs.configure.outputs.environment }}
      project-name: ${{ matrix.project }}
      deploy-type: "static"
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
>>>>>>> 46ef1fee2562a397e75dc75d8aa1b3e2356c30e9
